"""Creación inicial

Revision ID: 37864ca8a04f
Revises: 
Create Date: 2025-11-03 15:26:19.824711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37864ca8a04f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recuerdo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('archivo', sa.String(length=300), nullable=True),
    sa.Column('tipo', sa.String(length=10), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recuerdo')
    # ### end Alembic commands ###
